// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Account struct {
	ID            int64     `json:"id"`
	AccountName   string    `json:"account_name"`
	AccountNumber int64     `json:"account_number"`
	PhoneNumber   int64     `json:"phone_number"`
	Email         string    `json:"email"`
	Status        string    `json:"status"`
	Balance       int64     `json:"balance"`
	CurrencyCode  string    `json:"currency_code"`
	CreatedAt     time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
